released version in MX-14.3

diff --git a/snapshot-mx b/snapshot-mx
--- a/snapshot-mx
+++ b/snapshot-mx
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-version="snapshot-0.2.8 (03.03.2014)"
+version="snapshot-0.2.9 (22.11.2014)"
+ME=${0##*/}
 # adapted for MX-14 by anticapitalista@operamail.com 
 # from version="refractasnapshot-9.0.6-2 (20121026)" by fsmithred@gmail.com
 # which was based primarily on refractasnapshot-8.0.4  by Dean Linkous with ideas
@@ -73,6 +74,7 @@ work_dir=${work_dir:="/home/work"}
 snapshot_dir=${snapshot_dir:="/home/snapshot"}
 save_work=${save_work:="no"}
 snapshot_excludes=${snapshot_excludes:="/usr/lib/snapshot-mx/snapshot_exclude.list"}
+initrd_modules_file=${initrd_modules_file:="/usr/lib/snapshot-mx/initrd_modules.list"}
 snapshot_persist=${snapshot_persist:="no"}
 kernel_image=${kernel_image:="/vmlinuz"}
 initrd_image=${initrd_image:="/initrd.gz"}
@@ -225,18 +227,59 @@ check_space
 detect_kernels
 report_space
 
+copy_modules() {
+    local to=$1  from=$2 ; shift 2
+
+    local list
+    if [ -f $1 ]; then
+        list=$(cat $1)
+    else
+        list="$*"
+    fi
+   
+    local name mod expr
+    for name in $list; do
+        mod=$(echo $name | sed -e 's/[_-]/[_-]/g' -e 's/$/.ko/')
+        expr="$expr${expr:+ -o} -name $mod"
+    done
+
+    mkdir -p $to
+
+    local mod_list=$(find $from $expr)
+    local count=$(echo "$mod_list" | grep -c .)
+    printf $"Copying %s modules into the initrd\n" $count
+
+    local file sub_dir
+    for file in $mod_list; do
+        #[ "$verbose" ] && echo "Add initrd module $(basename $file .ko)"
+        sub_dir="$to/$(basename $(dirname $file))"
+        mkdir -p $sub_dir
+        cp $file $sub_dir/
+    done
+}
+
+open_initrd() {
+    local file=$1  dir=$2
+    mkdir -p $dir
+    chmod a+rx $dir
+    (cd $dir && gunzip -c $file | cpio -idum)
+}
+
+close_initrd() {
+    local dir=$1  file=$2
+    (cd $dir && find . | cpio -o -H newc --owner root:root | gzip -9) > $file
+    #rm -rf $dir
+}
+ 
+if [ ! -e "$initrd_modules_file" ]; then
+    echo "Could not find list of modules to put into the initrd"
+    echo "Missing file: $initrd_modules_file"
+    exit 2
+fi
+
 
 # The real work starts here
 cd $work_dir
-
-# Run ps_initrd.sh to set up live initrd.gz
-#ps_initrd.sh "$iso_dir"/antiX/initrd.gz open 
-#cd "$iso_dir"/antiX/initrd.gz-image/"$lib_mod_dir"/
-#mkdir $kernel_used
-#cp -R "$lib_mod_dir"/$kernel_used/"$ata_dir" "$iso_dir"/antiX/initrd.gz-image/"$lib_mod_dir"/$kernel_used/
-#ps_initrd.sh "$iso_dir"/antiX/initrd.gz close
-
-#cd $work_dir
 
 #copy correct vmlinuz to "$work_dir"/new-iso/
 echo "Copying the new-iso filesystem..."
@@ -244,6 +287,16 @@ cp /boot/vmlinuz-$kernel_used "$iso_dir"/antiX/vmlinuz
 rsync -a "$iso_dir"/ "$work_dir"/new-iso/ 
 rm "$iso_dir"/antiX/vmlinuz
 
+initrd_dir=$(mktemp -d /tmp/$ME-XXXXX)
+open_initrd $iso_dir/antiX/initrd.gz $initrd_dir
+
+mod_dir=$initrd_dir/lib/modules
+rm -rf $mod_dir/*
+copy_modules $mod_dir/$kernel_used /lib/modules/$kernel_used $initrd_modules_file
+
+close_initrd $initrd_dir $work_dir/new-iso/antiX/initrd.gz
+
+   
 # Copy the filesystem
 rsync -a / new-squashfs/ --delete --exclude="$work_dir" --exclude="$snapshot_dir" --exclude-from="$snapshot_excludes"
 
